import { AlertCircleIcon, CheckCircle2Icon, ExternalLinkIcon, ShieldCheckIcon, UsersRoundIcon } from 'lucide-react';

const evidenceRows = [
  { weight: '20%', criterion: 'Active participation', claim: 'Sustained work across Flair Club, ACS, G17, NCPA, Sasnaka Sansada, teaching and event logistics.', proof: 'LinkedIn role history, appointment letters, activity photographs and programme records.', status: 'available' },
  { weight: '15%', criterion: 'Commitment to the team', claim: 'Continuous community involvement from 2022 and responsibility maintained through delivery and follow-up.', proof: 'Dated role records, appreciation letters and a referee statement confirming reliability.', status: 'mixed' },
  { weight: '15%', criterion: 'Flexibility', claim: 'Served as secretary, panel lead, ambassador, educator, facilitator, logistics support and project contributor.', proof: 'Role descriptions plus one captioned example explaining why each role change was needed.', status: 'mixed' },
  { weight: '20%', criterion: 'Co-operation & presentation', claim: 'Coordinated handoffs and communicated with students, organisers, volunteers, partners and community participants.', proof: 'EduACS programme record, facilitation photographs and teammate verification.', status: 'mixed' },
  { weight: '10%', criterion: 'Respecting team members', claim: 'Listens before deciding, protects dignity, makes room for different views and shares credit.', proof: 'Add permission-approved teammate statements describing a specific observed behaviour.', status: 'needed' },
  { weight: '20%', criterion: 'Overall assessment', claim: 'Consistent team-first narrative supported by service history, outcomes, recognition and honest reflection.', proof: 'Portfolio, CV, LinkedIn, recognition records and named referees available to judges.', status: 'available' },
];

const echoRequests = [
  { title: 'A teammate under pressure', prompt: 'One specific moment when listening or practical support helped them contribute.' },
  { title: 'A successor or newer member', prompt: 'What remained useful after the formal role or handover ended.' },
  { title: 'A cross-team collaborator', prompt: 'How communication helped two groups work toward the same outcome.' },
];

export function EvidenceSection() {
  return <section id="evidence" className="py-20 md:py-28 relative" aria-labelledby="evidence-heading"><div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10 relative z-10">
    <header className="text-center max-w-3xl mx-auto mb-12"><p className="text-blue-400 font-mono text-xs tracking-[0.32em] uppercase mb-4">05 - Evidence, not decoration</p><h2 id="evidence-heading" className="text-3xl sm:text-5xl font-extrabold text-white">Proof, gaps and <span className="text-blue-400">named voices.</span></h2><p className="text-gray-400 text-lg mt-5">A strong submission distinguishes evidence already available from evidence that still needs a witness or supporting document.</p></header>
    <div className="rounded-3xl border border-white/12 bg-[#0b1526]/90 overflow-hidden">{evidenceRows.map((row, index) => <article key={row.criterion} className={`grid lg:grid-cols-[0.16fr_0.45fr_0.95fr_1.15fr] gap-4 p-5 sm:p-6 items-start ${index ? 'border-t border-white/10' : ''}`}><div className="text-2xl font-extrabold text-amber-300">{row.weight}</div><div><h3 className="text-white font-bold">{row.criterion}</h3><Status status={row.status} /></div><p className="text-gray-300 leading-relaxed">{row.claim}</p><div><p className="text-xs uppercase tracking-[0.14em] text-blue-400 font-semibold">Evidence / action</p><p className="text-gray-400 text-sm leading-relaxed mt-2">{row.proof}</p></div></article>)}</div>
    <div className="mt-10"><div className="flex items-end justify-between gap-4 mb-5"><div><p className="text-blue-400 text-xs uppercase tracking-[0.16em] font-semibold">Team Echo Wall</p><h3 className="text-white text-2xl font-bold mt-1">Voices unlock only with permission.</h3></div><UsersRoundIcon className="w-8 h-8 text-blue-400" /></div><div className="grid md:grid-cols-3 gap-5">{echoRequests.map((echo) => <article key={echo.title} className="rounded-2xl border border-dashed border-white/15 bg-white/[0.02] p-6"><div className="w-9 h-9 rounded-full border border-white/10 flex items-center justify-center text-gray-500">“ ”</div><h4 className="text-white font-semibold mt-5">{echo.title}</h4><p className="text-gray-500 text-sm mt-2 leading-relaxed">{echo.prompt}</p><span className="inline-flex mt-5 px-2.5 py-1 rounded-full bg-amber-400/10 text-amber-300 text-[10px] uppercase tracking-wider">Awaiting approved quote</span></article>)}</div></div>
    <div className="mt-8 grid md:grid-cols-[1.25fr_0.75fr] gap-5"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.06] p-6 flex gap-4"><ShieldCheckIcon className="w-7 h-7 text-emerald-400 shrink-0" /><div><h3 className="font-bold text-white">Evidence integrity rule</h3><p className="text-gray-300 mt-1">No anonymous praise, continuity percentage or emotional-support story is presented as proof without permission and a specific observed example.</p></div></div><a href="https://www.linkedin.com/in/vihanga-rathnayake-a6a652321/" target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-blue-400/20 bg-blue-400/[0.06] p-6 flex items-center justify-between text-white font-semibold">Review public role record <ExternalLinkIcon className="w-5 h-5 text-blue-300" /></a></div>
  </div></section>;
}

function Status({ status }: { status: string }) { const ready = status === 'available'; const needed = status === 'needed'; return <span className={`inline-flex items-center gap-1.5 mt-2 text-xs ${ready ? 'text-emerald-300' : needed ? 'text-rose-300' : 'text-amber-300'}`}>{ready ? <CheckCircle2Icon className="w-3.5 h-3.5" /> : <AlertCircleIcon className="w-3.5 h-3.5" />}{ready ? 'Available' : needed ? 'Must add' : 'Strengthen'}</span>; }
