import { useEffect, useState } from 'react';
import { ChevronLeftIcon, ChevronRightIcon, PinIcon, PresentationIcon, XIcon } from 'lucide-react';

const stops = [
  { id: 'home', label: 'Philosophy', target: '0:00-1:00', prompt: 'One sentence: who am I when a team is under pressure?' },
  { id: 'stories', story: '01', label: "Flagship: Dhaara '24", target: '1:00-3:30', prompt: 'Pressure, role switches, support action, collective result.' },
  { id: 'stories', story: '02', label: 'Shared ownership: EduACS', target: '3:30-5:30', prompt: 'Show how the system reduced dependence on one person.' },
  { id: 'stories', story: '03', label: 'Empathy: LearnLift', target: '5:30-7:00', prompt: 'Explain how context changed the way the team communicated.' },
  { id: 'evidence', label: 'Invisible work & voices', target: '7:00-8:00', prompt: 'Show one pinned proof item and one teammate voice when approved.' },
  { id: 'growth', label: 'Pressure & growth', target: '8:00-9:00', prompt: 'Name what changed after last year and what you now do differently.' },
  { id: 'contact', label: 'Collective impact close', target: '9:00-10:00', prompt: 'End with the signature line; stop before the timer reaches zero.' },
];

type Pinned = { title: string; evidence: string };
export function PresentationControls() {
  const [active, setActive] = useState(false); const [index, setIndex] = useState(0); const [seconds, setSeconds] = useState(600); const [pinned, setPinned] = useState<Pinned | null>(null);
  const start = () => { setActive(true); setIndex(0); setSeconds(600); document.documentElement.classList.add('presentation-mode'); document.getElementById(stops[0].id)?.scrollIntoView(); };
  const stop = () => { setActive(false); document.documentElement.classList.remove('presentation-mode'); };
  useEffect(() => { const onStart = () => start(); const onPin = (event: Event) => setPinned((event as CustomEvent<Pinned>).detail); window.addEventListener('start-presentation', onStart); window.addEventListener('pin-evidence', onPin); return () => { window.removeEventListener('start-presentation', onStart); window.removeEventListener('pin-evidence', onPin); }; }, []);
  useEffect(() => { if (!active || seconds <= 0) return; const timer = window.setInterval(() => setSeconds((value) => value - 1), 1000); return () => window.clearInterval(timer); }, [active, seconds]);
  const move = (next: number) => { const safe = Math.max(0, Math.min(stops.length - 1, next)); setIndex(safe); const step = stops[safe]; if ('story' in step && step.story) window.dispatchEvent(new CustomEvent('open-story', { detail: step.story })); document.getElementById(step.id)?.scrollIntoView({ behavior: 'smooth' }); };
  if (!active) return <button onClick={start} className="presentation-launch fixed bottom-5 right-5 z-50 px-4 py-3 rounded-xl bg-blue-600 text-white shadow-xl flex items-center gap-2 text-sm font-semibold"><PresentationIcon className="w-4 h-4" /> Story Path</button>;
  const clock = `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`; const progress = ((600 - seconds) / 600) * 360;
  return <div className="fixed inset-x-0 bottom-0 z-[80] bg-[#07111f]/95 backdrop-blur-xl border-t border-blue-400/20"><div className="h-1 bg-white/10"><div className="h-full bg-gradient-to-r from-blue-400 to-amber-400 transition-all" style={{ width: `${((index + 1) / stops.length) * 100}%` }} /></div>{pinned && <div className="border-b border-white/10 px-4 py-2 text-xs flex items-center justify-center gap-2 text-gray-300"><PinIcon className="w-3.5 h-3.5 text-amber-300" /><strong className="text-white">{pinned.title}:</strong><span className="truncate max-w-2xl">{pinned.evidence}</span><button onClick={() => setPinned(null)} className="text-gray-500 ml-2" aria-label="Unpin evidence">×</button></div>}<div className="max-w-7xl mx-auto px-4 py-2.5 flex items-center justify-between gap-3"><div className="w-12 h-12 rounded-full p-1 flex items-center justify-center" style={{ background: `conic-gradient(#4da6ff ${progress}deg, rgba(255,255,255,.08) 0deg)` }}><div className="w-full h-full rounded-full bg-[#07111f] flex items-center justify-center"><span className={`font-mono text-[10px] ${seconds < 120 ? 'text-amber-300' : 'text-blue-300'}`}>{clock}</span></div></div><div className="hidden sm:block flex-1 text-center"><p className="text-xs text-white font-semibold">{stops[index].label} <span className="text-gray-500 font-normal">· {stops[index].target}</span></p><p className="text-[10px] text-gray-400 mt-1">{stops[index].prompt}</p></div><div className="flex items-center gap-2"><button onClick={() => move(index - 1)} disabled={index === 0} className="p-2 rounded-lg bg-white/10 disabled:opacity-30" aria-label="Previous story step"><ChevronLeftIcon className="w-4 h-4" /></button><span className="text-xs text-gray-400">{index + 1}/{stops.length}</span><button onClick={() => move(index + 1)} disabled={index === stops.length - 1} className="p-2 rounded-lg bg-white/10 disabled:opacity-30" aria-label="Next story step"><ChevronRightIcon className="w-4 h-4" /></button></div><button onClick={stop} className="p-2 rounded-lg bg-white/10" aria-label="Exit story path"><XIcon className="w-4 h-4" /></button></div></div>;
}
