import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRightIcon, BookOpenIcon, CalendarCheckIcon, ChevronDownIcon, EyeOffIcon, Globe2Icon, PinIcon } from 'lucide-react';
import { CriteriaHeatmap, type CriterionId } from './CriteriaHeatmap';

type Story = {
  number: string; icon: typeof CalendarCheckIcon; context: string; role: string; criteria: CriterionId[];
  goal: string; contribution: string; challenge: string; supported: string; adapted: string; result: string; evidence: string; lesson: string;
  roles: { title: string; moment: string }[];
};

const stories: Story[] = [
  { number: '01', icon: CalendarCheckIcon, context: "Flair Club / Dhaara '24", role: 'Secretary & behind-the-scenes contributor', criteria: ['participation', 'commitment', 'flexibility', 'cooperation'], goal: 'Deliver a reliable, well-coordinated participant experience for a large cultural event under time pressure.', contribution: 'Took ownership of venue readiness, equipment handovers, on-ground coordination and last-minute operational gaps so programme-facing members could stay focused.', challenge: 'Plans shifted close to the event. Several committees needed clearer revised responsibilities and some members were under visible pressure.', supported: 'Listened to affected committees, reorganised handovers, stayed present until the new sequence was clear and absorbed overflow logistics work.', adapted: 'Moved between secretary duties, logistics support and quiet facilitation depending on what the team needed in the moment.', result: 'The event was delivered by the organising team. My behind-the-scenes contribution was recognised with a Logistics & Facilitation Excellence Award.', evidence: 'Role record, recognition, event activity photographs and referee available to judges.', lesson: 'Team trust is built through small promises kept repeatedly when the pressure is highest.', roles: [ { title: 'Listener', moment: 'Heard the affected committees before revising the handovers.' }, { title: 'Coordinator', moment: 'Kept the changed sequence and responsibilities visible.' }, { title: 'Gap-filler', moment: 'Absorbed practical overflow when pressure increased.' }, { title: 'Quiet facilitator', moment: 'Stayed with the handover until every owner was clear.' }, { title: 'Credit-giver', moment: 'Kept the result framed as the organising team’s work.' } ] },
  { number: '02', icon: BookOpenIcon, context: 'ACS / EduACS', role: 'Co-founder & Secretary', criteria: ['participation', 'commitment', 'cooperation', 'overall'], goal: 'Create a repeatable team system that brings useful computing education to school students.', contribution: 'Helped design the operating rhythm and coordinated delivery, communication, quality checks and continuity.', challenge: 'Early sessions risked becoming dependent on a few individuals. Knowledge and responsibility needed to be shared.', supported: 'Created clear handoffs, supported newer volunteers to take real responsibility and ensured quieter contributors had meaningful tasks.', adapted: 'Shifted between co-founder, secretary, quality checker and quiet supporter as the team matured.', result: 'Public programme records report 1,000+ schoolchildren reached, with delivery structured around shared ownership.', evidence: 'Public programme record, role history, activity documentation and referee contact.', lesson: 'A good coordinator creates clarity without controlling every decision.', roles: [ { title: 'Listener', moment: 'Understood what volunteers needed before defining the workflow.' }, { title: 'System-builder', moment: 'Turned repeated work into clearer handoffs.' }, { title: 'Coordinator', moment: 'Connected delivery, communication and quality checks.' }, { title: 'Supporter', moment: 'Helped newer members take real responsibility.' }, { title: 'Handover partner', moment: 'Reduced dependence on one person or title.' } ] },
  { number: '03', icon: Globe2Icon, context: 'G17 LearnLift', role: 'University Ambassador & project contributor', criteria: ['flexibility', 'cooperation', 'respect', 'overall'], goal: 'Support learning and child-focused awareness in Monaragala under SDG 10 as part of a wider collaborative effort.', contribution: 'Contributed to awareness, child-protection and mathematics-focused activities while adapting communication to the community context.', challenge: 'Working across cultural and organisational differences required listening rather than imposing a campus-style approach.', supported: 'Prioritised understanding local context, supported the shared programme and avoided seeking a personal spotlight.', adapted: 'Moved between ambassador, facilitator and quiet team contributor according to what the project and community needed.', result: 'The contribution formed part of my G17 Ambassador of the Month recognition, shared with the wider team and community partners.', evidence: 'Ambassador role history, recognition record and programme activity evidence.', lesson: 'Empathy begins with understanding context before offering help.', roles: [ { title: 'Learner', moment: 'Entered the community context ready to understand first.' }, { title: 'Ambassador', moment: 'Connected the programme purpose with participants.' }, { title: 'Facilitator', moment: 'Adapted the message to the people in front of us.' }, { title: 'Contributor', moment: 'Supported the shared plan without seeking the spotlight.' }, { title: 'Respectful partner', moment: 'Measured value through relevance to the community.' } ] },
];

const invisibleWork = [
  { title: 'Before the programme', visible: 'A finished event plan', unseen: 'Checking venue readiness, equipment and handover ownership before anyone stepped on stage.' },
  { title: 'When plans changed', visible: 'A smooth revised sequence', unseen: 'Listening to affected members, clarifying the new owners and absorbing practical overflow.' },
  { title: 'After delivery', visible: 'A collective result', unseen: 'Closing handoffs, documenting continuity and giving the public credit back to the team.' },
];

export function ProjectsSection() {
  const [expanded, setExpanded] = useState('01');
  const [showInvisible, setShowInvisible] = useState(false);
  useEffect(() => { const openStory = (event: Event) => setExpanded((event as CustomEvent<string>).detail); window.addEventListener('open-story', openStory); return () => window.removeEventListener('open-story', openStory); }, []);
  const pin = (story: Story) => window.dispatchEvent(new CustomEvent('pin-evidence', { detail: { title: story.context, evidence: story.evidence } }));
  return <section id="stories" className="py-20 md:py-28 relative" aria-labelledby="stories-heading"><div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10 relative z-10">
    <header className="max-w-3xl mb-12"><p className="text-blue-400 font-mono text-xs tracking-[0.32em] uppercase mb-4">03 - Teamwork under pressure</p><h2 id="stories-heading" className="text-3xl sm:text-5xl font-extrabold text-white">The role changed. The <span className="text-blue-400">shared goal did not.</span></h2><p className="text-gray-400 text-lg mt-5">Open each story to see the pressure point, role changes, support given to others and collective result.</p></header>
    <div className="space-y-6">{stories.map((story) => { const Icon = story.icon; const open = expanded === story.number; return <motion.article key={story.context} layout className={`rounded-3xl border bg-[#0b1526]/90 overflow-hidden transition-colors ${open ? 'border-blue-400/30' : 'border-white/12'}`}>
      <button onClick={() => setExpanded(open ? '' : story.number)} className="w-full text-left p-6 sm:p-8" aria-expanded={open}><div className="flex items-start gap-5"><div className="w-12 h-12 rounded-xl bg-blue-400/10 flex items-center justify-center shrink-0"><Icon className="w-6 h-6 text-amber-400" /></div><div className="flex-1"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2"><div><span className="text-blue-400 font-mono text-xs">STORY {story.number}</span><h3 className="text-2xl font-bold text-white mt-1">{story.context}</h3><p className="text-gray-500 text-sm mt-1">{story.role}</p></div><ChevronDownIcon className={`w-5 h-5 text-gray-400 transition-transform ${open ? 'rotate-180' : ''}`} /></div><div className="mt-5"><CriteriaHeatmap active={open ? story.criteria : []} compact /></div></div></div></button>
      <AnimatePresence initial={false}>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="px-6 sm:px-8 pb-8 border-t border-white/10 pt-7">
        <CriteriaHeatmap active={story.criteria} />
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-6 mt-8"><StoryPoint label="Shared goal" text={story.goal} /><StoryPoint label="My contribution" text={story.contribution} /><StoryPoint label="Challenge / pressure" text={story.challenge} /><StoryPoint label="How I supported others" text={story.supported} /><StoryPoint label="How I adapted" text={story.adapted} /><StoryPoint label="Collective result" text={story.result} /></div>
        <div className="mt-8"><p className="text-xs uppercase tracking-[0.16em] text-blue-400 font-semibold">Role fluidity map</p><div className="flex flex-col lg:flex-row gap-2 mt-4">{story.roles.map((role, index) => <div key={role.title} className="group relative flex-1"><div className="rounded-xl border border-white/10 bg-white/[0.03] p-4 h-full hover:border-amber-400/25"><p className="text-white text-sm font-semibold">{role.title}</p><p className="text-gray-500 text-xs mt-2 leading-relaxed group-hover:text-gray-300 transition-colors">{role.moment}</p></div>{index < story.roles.length - 1 && <ArrowRightIcon className="hidden lg:block absolute -right-2.5 top-1/2 w-4 h-4 text-blue-400 z-10" />}</div>)}</div></div>
        <div className="mt-7 pt-5 border-t border-white/10 grid sm:grid-cols-[1fr_1fr_auto] gap-5 items-start"><div className="flex gap-3 text-amber-200"><ArrowRightIcon className="w-5 h-5 shrink-0 mt-0.5" /><p><strong>Lesson:</strong> {story.lesson}</p></div><div><p className="text-xs uppercase tracking-[0.14em] text-emerald-400 font-semibold">Verification route</p><p className="text-gray-400 text-sm mt-1">{story.evidence}</p></div><button onClick={() => pin(story)} className="inline-flex items-center gap-2 px-3 py-2 rounded-lg border border-blue-400/20 text-blue-300 text-xs"><PinIcon className="w-3.5 h-3.5" /> Pin evidence</button></div>
      </div></motion.div>}</AnimatePresence>
    </motion.article>; })}</div>
    <div className="mt-8 rounded-3xl border border-amber-400/20 bg-amber-400/[0.04] overflow-hidden"><button onClick={() => setShowInvisible((value) => !value)} className="w-full p-6 sm:p-8 flex items-center justify-between gap-4 text-left"><div className="flex gap-4"><EyeOffIcon className="w-7 h-7 text-amber-300 shrink-0" /><div><p className="text-xs uppercase tracking-[0.16em] text-amber-300">Invisible work layer</p><h3 className="text-white text-xl sm:text-2xl font-bold mt-1">What the audience never saw on stage</h3></div></div><ChevronDownIcon className={`w-5 h-5 text-gray-400 transition-transform ${showInvisible ? 'rotate-180' : ''}`} /></button><AnimatePresence>{showInvisible && <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden"><div className="grid md:grid-cols-3 gap-4 px-6 sm:px-8 pb-8">{invisibleWork.map((item) => <article key={item.title} className="rounded-2xl border border-white/10 bg-[#081426]/80 p-5"><p className="text-blue-300 text-xs font-semibold uppercase tracking-wider">{item.title}</p><p className="text-gray-500 text-sm mt-4">Visible: {item.visible}</p><p className="text-white mt-2 leading-relaxed">Unseen: {item.unseen}</p></article>)}</div></motion.div>}</AnimatePresence></div>
  </div></section>;
}

function StoryPoint({ label, text }: { label: string; text: string }) { return <div><p className="text-xs uppercase tracking-[0.16em] text-blue-400 font-semibold">{label}</p><p className="text-gray-300 leading-relaxed mt-2">{text}</p></div>; }
